Repository qmk/qmk_distro_msys, pull requests merged in 2021-01, with the labels that each got.

#4 Add links to the tutorial and highlight the Windows requirement
  docs/.vuepress/config.js
  docs/README.md
  docs/guide.md
Labels: documentation, enhancement

#11 Force terminal title to 'QMK MSYS'
  install.iss
Labels: enhancement

#12 Add example of how to configure Windows Terminal
  .github/workflows/docs.yml
  docs/faq.md
Labels: documentation

#15 Fix dependency upgrade workflow
  .env
  .github/workflows/build.yml
  .github/workflows/deps.yml
Labels: bug

#17 Stash some build info to help with diagnosis
  .github/workflows/build.yml
  src/etc/qmk-release
Labels: enhancement

#6 Remove beta status warning
  README.md
  docs/README.md
Labels: documentation

#24 Override PS1 to avoid printing terminal type
  src/etc/post-install/99-qmk.post
Labels: enhancement

#22 Force utf8 for qmk commands
  .github/workflows/build.yml
Labels: enhancement
